"""
Combine MP3 Chunks into Single MP3 File

This script combines all MP3 chunks generated by convert_pcm_to_mp3_chunks_by_frame.py
into a single MP3 file for final playback.

Usage:
    python combined_all_mp3_chunks_by_frame_into_a_single_mp3.py

Requirements:
    - ffmpeg must be installed and available in PATH
    - MP3 chunks should be in frames_aligned_mp3_chunks directory
    - Chunks should be named: chunk_0.mp3, chunk_1.mp3, chunk_2.mp3, etc.

Output:
    - Creates combined_output.mp3 in the same directory as the script
"""

import os
import subprocess
import argparse
import glob
import re

def combine_mp3_chunks(chunks_dir='frames_aligned_mp3_chunks', output_file='combined_output.mp3'):
    """
    Combine all MP3 chunks into a single MP3 file
    """
    try:
        # Get the directory of this script
        script_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Determine chunks directory path
        if os.path.isabs(chunks_dir):
            chunks_path = chunks_dir
        else:
            chunks_path = os.path.join(script_dir, chunks_dir)
        
        # Create mp3_combined directory and determine output file path
        mp3_combined_dir = os.path.join(script_dir, 'mp3_combined')
        os.makedirs(mp3_combined_dir, exist_ok=True)
        
        if os.path.isabs(output_file):
            output_path = output_file
        else:
            output_path = os.path.join(mp3_combined_dir, output_file)
        
        print(f"Chunks directory: {chunks_path}")
        print(f"Output file: {output_path}")
        
        # Check if chunks directory exists
        if not os.path.exists(chunks_path):
            print(f"Error: Chunks directory {chunks_path} not found!")
            return
        
        # Find all chunk MP3 files
        chunk_pattern = os.path.join(chunks_path, "chunk_*.mp3")
        chunk_files = glob.glob(chunk_pattern)
        
        if not chunk_files:
            print(f"Error: No chunk files found in {chunks_path}")
            return
        
        # Sort chunks by number (chunk_0.mp3, chunk_1.mp3, etc.)
        def extract_chunk_number(filename):
            match = re.search(r'chunk_(\d+)\.mp3', filename)
            return int(match.group(1)) if match else 0
        
        chunk_files.sort(key=extract_chunk_number)
        
        print(f"Found {len(chunk_files)} chunk files:")
        for i, chunk_file in enumerate(chunk_files[:5]):  # Show first 5
            print(f"  {i}: {os.path.basename(chunk_file)}")
        if len(chunk_files) > 5:
            print(f"  ... and {len(chunk_files) - 5} more")
        
        # Create temporary file list for ffmpeg concat
        concat_file = os.path.join(script_dir, 'temp_concat_list.txt')
        with open(concat_file, 'w') as f:
            for chunk_file in chunk_files:
                # Use relative path to avoid issues with spaces in paths
                rel_path = os.path.relpath(chunk_file, script_dir)
                f.write(f"file '{rel_path}'\n")
        
        try:
            # Use ffmpeg to concatenate MP3 files
            ffmpeg_cmd = [
                'ffmpeg',
                '-y',  # Overwrite output file
                '-f', 'concat',  # Use concat demuxer
                '-safe', '0',  # Allow unsafe file names
                '-i', concat_file,  # Input file list
                '-c', 'copy',  # Copy streams without re-encoding
                output_path
            ]
            
            print(f"\nCombining {len(chunk_files)} chunks...")
            result = subprocess.run(ffmpeg_cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"Error combining chunks: {result.stderr}")
                return
            
            # Get output file size
            if os.path.exists(output_path):
                output_size = os.path.getsize(output_path)
                print(f"\n✓ Successfully combined chunks into: {os.path.basename(output_path)}")
                print(f"✓ Output file size: {output_size/1024/1024:.1f} MB")
            else:
                print("Error: Output file was not created")
        
        finally:
            # Clean up temporary concat file
            if os.path.exists(concat_file):
                os.unlink(concat_file)
        
    except Exception as e:
        print(f"Error combining chunks: {e}")

def main():
    """Main function, handling command line arguments"""
    parser = argparse.ArgumentParser(
        description="Combine MP3 chunks into a single MP3 file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage with default settings
  python combined_all_mp3_chunks_by_frame_into_a_single_mp3.py
  
  # Custom chunks directory
  python combined_all_mp3_chunks_by_frame_into_a_single_mp3.py --chunks-dir my_chunks
  
  # Custom output file
  python combined_all_mp3_chunks_by_frame_into_a_single_mp3.py --output final_audio.mp3
        """
    )
    
    parser.add_argument('--chunks-dir', 
                       default='frames_aligned_mp3_chunks',
                       help='Directory containing MP3 chunks (default: frames_aligned_mp3_chunks)')
    
    parser.add_argument('--output', 
                       default='combined_output.mp3',
                       help='Output MP3 file name (default: combined_output.mp3)')
    
    args = parser.parse_args()
    
    # Check if ffmpeg is available
    try:
        subprocess.run(['ffmpeg', '-version'], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("Error: ffmpeg is not installed or not in PATH!")
        print("Please install ffmpeg: https://ffmpeg.org/download.html")
        return
    
    # Combine chunks
    combine_mp3_chunks(args.chunks_dir, args.output)

if __name__ == "__main__":
    main()
